# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 14:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swag', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='logo_url',
            field=models.CharField(default='', max_length=128),
        ),
    ]
