# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swag', '0002_show_logo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='favoriteshow',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='favoriteteam',
            name='notifications',
            field=models.BooleanField(default=True),
        ),
    ]
