# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swag', '0004_auto_20160227_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='league',
            field=models.CharField(choices=[('MLB', 'Major League Baseball'), ('NBA', 'National Basketball Association'), ('NFL', 'National Football League'), ('NHL', 'National Hockey League')], max_length=8),
        ),
    ]
