# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swag', '0005_auto_20160227_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='thumbnail_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='episode',
            name='video_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='game',
            name='thumbnail_url',
            field=models.CharField(default='', max_length=256),
        ),
        migrations.AddField(
            model_name='game',
            name='video_url',
            field=models.CharField(default='', max_length=256),
        ),
    ]
