# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-27 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swag', '0006_auto_20160227_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='swag.Show'),
        ),
    ]
